language: go

go:
  - '1.13'
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

go_import_path: github.com/reactivex/rxgo

install:
  - go get ./...

script:
  - go test -v -race -cover -coverprofile=/tmp/coverage.out
  - goveralls -coverprofile /tmp/coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN

notifications:
  webhooks:
    urls:
      - $GITTER_WEBHOOKS
    on_success: change
    on_failure: always
    on_start: never
